version: "3.8"

services:

  gofractal-node:

    build: wvk2017/fb
    container_name: gofractal-node

    restart: unless-stopped

    ports:
      - "32126:32126"

    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/pool/www:/www
      - ${APP_DATA_DIR}/data/node:/data
      - ${APP_DATA_DIR}/data/templates/bitcoind-entrypoint.sh:/bitcoind-entrypoint.sh:ro
      - ./scripts:/scripts

    command: >
      sh -c "
      chmod +x /scripts/register_coin.sh &&
      /scripts/register_coin.sh &&
      bitcoind -datadir=/data
      "

volumes:
  fractal-data:
